In [94]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
from scipy import stats
from scipy.stats import norm, skew

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import KFold
from sklearn.preprocessing import PolynomialFeatures

In [93]:
data = pd.read_csv('E:/Engineering 2020/Semester 10/Machine Learning/github/Machine_Learning_Assignments/house_prices_data_training_data.csv').to_numpy()
X=data[0:17999,3:21].astype(np.float64)
y=data[0:17999,2:3].astype(np.float64)
print(X[:,0])
print(y)

[3. 3. 2. ... 2. 3. 2.]
[[221900.]
 [538000.]
 [180000.]
 ...
 [253000.]
 [630000.]
 [216000.]]


There are 4 main features that have 80% & above null values. These we can delete. We can also delete the 'Id' column.

In [5]:
def computeCost(X, y, theta):
    """
    Compute cost for linear regression. Computes the cost of using theta as the
    parameter for linear regression to fit the data points in X and y.
    
    Parameters
    ----------
    X : array_like
        The input dataset of shape (m x n+1), where m is the number of examples,
        and n is the number of features. We assume a vector of one's already 
        appended to the features so we have n+1 columns.
    
    y : array_like
        The values of the function at each data point. This is a vector of
        shape (m, ).
    
    theta : array_like
        The parameters for the regression function. This is a vector of 
        shape (n+1, ).
    
    Returns
    -------
    J : float
        The value of the regression cost function.
    
    Instructions
    ------------
    Compute the cost of a particular choice of theta. 
    You should set J to the cost.
    """
    
    # initialize some useful values
    m = y.size  # number of training examples
    
    # You need to return the following variables correctly

    
    J = 0
    
    # ====================== YOUR CODE HERE =====================
    h = X.dot(theta)
    
    J = 1/(2*m)*np.sum(np.square(h-y))
    
    # ===========================================================
    return J

In [28]:
def gradientDescent(X, y, theta, alpha, num_iters):
    """
    Performs gradient descent to learn `theta`. Updates theta by taking `num_iters`
    gradient steps with learning rate `alpha`.
    
    Parameters
    ----------
    X : array_like
        The input dataset of shape (m x n+1).
    
    y : arra_like
        Value at given features. A vector of shape (m, ).
    
    theta : array_like
        Initial values for the linear regression parameters. 
        A vector of shape (n+1, ).
    
    alpha : float
        The learning rate.
    
    num_iters : int
        The number of iterations for gradient descent. 
    
    Returns
    -------
    theta : array_like
        The learned linear regression parameters. A vector of shape (n+1, ).
    
    J_history : list
        A python list for the values of the cost function after each iteration.
    
    Instructions
    ------------
    Peform a single gradient step on the parameter vector theta.

    While debugging, it can be useful to print out the values of 
    the cost function (computeCost) and gradient here.
    """
    # Initialize some useful values
    m = y.shape[0]  # number of training examples
    
    # make a copy of theta, to avoid changing the original array, since numpy arrays
    # are passed by reference to functions
    theta = theta.copy()
    
    J_history = [] # Use a python list to save cost in every iteration
    
    for i in range(num_iters):
        alphabym=alpha/m
        sumofh0x=np.dot(X,theta)
        theta=theta-((alpha/m)*(np.dot(X.T,sumofh0x-y)))

        # save the cost J in every iteration
        J_history.append(computeCost(X, y, theta))
    
    return theta, J_history

Using model selection to check the error of using many features


In [81]:
#this function is looping for computing error while using many features starting from 1 to over fit all the data
def feature_looping (X,y):
    for i in range (17):
        # initialize fitting parameters
        theta = np.zeros(X.shape[0])

        # some gradient descent settings
        iterations = 1500
        alpha = 0.01
        print((gradientDescent(X[:,i] ,y, theta, alpha, iterations))[1])

    return J_history

In [82]:
def  featureNormalize(X):
    """
    Normalizes the features in X. returns a normalized version of X where
    the mean value of each feature is 0 and the standard deviation
    is 1. This is often a good preprocessing step to do when working with
    learning algorithms.
    
    Parameters
    ----------
    X : array_like
        The dataset of shape (m x n).
    
    Returns
    -------
    X_norm : array_like
        The normalized dataset of shape (m x n).
    
    Instructions
    ------------
    First, for each feature dimension, compute the mean of the feature
    and subtract it from the dataset, storing the mean value in mu. 
    Next, compute the  standard deviation of each feature and divide
    each feature by it's standard deviation, storing the standard deviation 
    in sigma. 
    
    Note that X is a matrix where each column is a feature and each row is
    an example. You needto perform the normalization separately for each feature. 
    
    Hint
    ----
    You might find the 'np.mean' and 'np.std' functions useful.
    """
    # You need to set these values correctly
    X_norm = X.copy()
    #mu = np.zeros(X.shape[1])
    #sigma = np.zeros(X.shape[1])

    # =========================== YOUR CODE HERE =====================
    means= X.mean(axis=0)
    #Then find standard deviation
    stds=X.std(axis=0)
    #Getting scaled data
    X_norm =(X- means) / stds
    
    #mu=X_norm.mean(axis=0)
    #sigma=X_norm.std(axis=0)
        
    # ================================================================
    return X_norm

In [107]:
#train test split
x, X_test, ya, y_test = train_test_split(X,y,test_size=0.2,train_size=0.8,random_state=0)
X_train, X_cv, y_train, y_cv = train_test_split(x,ya,test_size = 0.2,train_size =0.8,random_state=0)
X_normalized= featureNormalize(X_train)
X_normalized_test= featureNormalize(X_test)
print(X_normalized.shape)
print(y_train.shape)

(11519, 18)
(11519, 1)


In [108]:
feature_looping(X_normalized,y_train)

[208311694488.9335, 208311694488.9324, 208311694488.93317, 208311694488.93024, 208311694488.93076, 208311694488.93173, 208311694488.92642, 208311694488.92587, 208311694488.92932, 208311694488.9269, 208311694488.9232, 208311694488.92517, 208311694488.92004, 208311694488.91565, 208311694488.9232, 208311694488.9174, 208311694488.91287, 208311694488.92474, 208311694488.91116, 208311694488.91925, 208311694488.92065, 208311694488.9194, 208311694488.9031, 208311694488.92325, 208311694488.8962, 208311694488.90237, 208311694488.9119, 208311694488.8967, 208311694488.91257, 208311694488.91336, 208311694488.89023, 208311694488.8998, 208311694488.90155, 208311694488.9144, 208311694488.9326, 208311694488.90976, 208311694488.91318, 208311694488.88538, 208311694488.8904, 208311694488.91614, 208311694488.905, 208311694488.91257, 208311694488.88657, 208311694488.88657, 208311694488.93677, 208311694488.89352, 208311694488.87863, 208311694488.89938, 208311694488.88766, 208311694488.87427, 208311694488.907

array([0., 0., 0., ..., 0., 0., 0.])

In [120]:
#using scikit learn
model=LinearRegression().fit(X_normalized,y_train)
y_predicted=model.predict(X_normalized_test)
y_val=y_test-y_predicted
m=X_normalized_test.size
error=(1/(2*m))*np.dot(y_val.T,y_val)
print('The error is: {:s}'.format(str(error)))


The error is: [[1.19857739e+09]]


In [ ]:
#Polynimoial features
for i in range (3):
    features=PolynomialFeatures(degree=i+2,include_bias=False).fit_transform(X_normalized)
    model_poly=LinearRegression().fit(features,y_train)
    y_predicted=model.predict(X_normalized_test)
    y_val=y_test-y_predicted
    m=X_normalized_test.size
    error=(1/(2*m))*np.dot(y_val.T,y_val)
    print('The error is: {:s}'.format(str(error)))


The error is: [[1.19857739e+09]]
The error is: [[1.19857739e+09]]


In this reprot I have performed some model selection techniques.
I have used sklearn to create its own model and uses various polynomial degrees.
It is clear from the results above that linear model is not a perfect choice.
